sonar.projectKey=sonar-clojure
sonar.projectName=sonar-clojure
sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.clojure.kondo.reportPaths=target/clj-kondo.json
sonar.clojure.kondo.analysisPaths=target/clj-kondo-analysis.json
sonar.clojure.cloverage.reportPaths=target/coverage/codecov.json

